#!/usr/bin/env bash

# mostly from: https://dev.to/bdelespierre/how-to-setup-git-commit-hooks-for-php-42d1

# get bash colors and styles here: 
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}COMMIT FAILED!${C_RESET}\n\n$output"
        exit 1
    fi
}

__run "1/1" "PHP Linter. It will attempt fixes, then may generate a report of things you must manually fix. " "COMPOSE_IGNORE_ORPHANS=True docker compose run -T --rm app bash -c '../vendor/bin/phpcbf wp-content/*/kdc-*; ../vendor/bin/phpcs -w wp-content/*/kdc-*'"
